#!/bin/bash

read -p "Enter a number: " n

while [[ $n -le 0 ]]; do
    echo "Please enter a positive number."
    read -p "Enter a number: " n
done

sum=0
i=1

while [[ $i -le $n ]]; do
    sum=$((sum + i))
    ((i++))
done

echo "Sum of first $n numbers is: $sum"
