#!/bin/bash
sum_of_numbers() {
    local n=$1
    local sum=0
    local i=1

    while [[ $i -le $n ]]; do
        sum=$((sum + i))
        ((i++))
    done

    echo $sum
}

read -p "Enter a number: " n

if [[ $n -le 0 ]]; then
    echo "Please enter a positive number."
else
    result=$(sum_of_numbers $n)
    echo "Sum of first $n numbers is: $result"
fi
