#!/bin/bash

sum_of_numbers() {
    local n=$1
    local sum=0
    local i=1

    while [[ $i -le $n ]]; do
        sum=$((sum + i))
        ((i++))
    done

    echo $sum
}

until [[ $n -gt 0 ]]; do
    read -p "Enter a positive number: " n
    if [[ $n -le 0 ]]; then
        echo "Please enter a positive number."
    fi
done

result=$(sum_of_numbers $n)
echo "Sum of first $n numbers is: $result"
