#!/bin/bash

until [[ $n -gt 0 ]]; do
    read -p "Enter a positive number: " n
    [[ $n -le 0 ]] && echo "Please enter a positive number."
done

sum=0
for ((i=1; i<=n; i++)); do
    sum=$((sum + i))
done

echo "Sum of first $n numbers is: $sum"
